version: '3'
services:

  scraper-web:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/scraper-web:latest
    ports:
      - 8080:80
    links:
      - scraper-app
    volumes:
      - "/home/ec2-user/docker/nginx/libs:/usr/share/nginx/html"
    logging:
      driver: awslogs
      options:
        awslogs-group: scraper-web-lg
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: scraper-web

  scraper-app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/scraper-app:latest
    ports:
      - 8085:8085
    links:
      - scraper-db
    volumes:
      - "/home/ec2-user/docker/scraper/logs:/root/scraper/logs"
    command: bash -c "sleep 30; cd /root/scraper/; java -jar web-scraper-server-*.jar --rest --spring.config.location=file:application.yaml"
    logging:
      driver: awslogs
      options:
        awslogs-group: scraper-app-lg
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: scraper-app

  scraper-db:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/scraper-db:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: web_scraper
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - "/home/ec2-user/docker/mysql/conf.d:/etc/mysql/conf.d"
      - "/home/ec2-user/docker/mysql/initdb.d:/root/mysql/initdb.d"
      - "/home/ec2-user/docker/mysql/jobs.d:/root/mysql/jobs.d"
      - "/home/ec2-user/docker/mysql/data:/var/lib/mysql"
      - "/home/ec2-user/docker/mysql/logs:/var/log/mysql"
      - "/home/ec2-user/docker/mysql/backup:/root/mysql/backup"
    logging:
      driver: awslogs
      options:
        awslogs-group: scraper-db-lg
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: scraper-db
